### ISSUE TITLE
Using Display Features plugin halts all GA functionality

### ISSUE THREAD

**Issue by jehartzog** [react-ga/react-ga#129]
I'm using react-ga in a Meteor project and noticed that GA wasn't receiving my data. After using the GA chrome plugin, I found that when using the [display features](https://developers.google.com/analytics/devguides/collection/analyticsjs/display-features) plugin, the GA script would get hung on waiting for a response and not send out any data.

Here is my init code:
```
Meteor.startup(() => {
  ReactGA.initialize(Meteor.settings.public.gaTrackingId);
  ReactGA.plugin.require('displayFeatures');
  ReactGA.plugin.require('linkid');
  ReactGA.plugin.require('ec');
});
```
Console output using GA chrome plugin which is repeated everytime a call is made to react-ga:
```
Running command: ga("require", "displayFeatures")
Waiting on require of "displayFeatures" to be fulfilled.
```
For now I simply disabled display features, and I'm not even sure this is a react-ga issue, but posting here in case someone else sees this issue.

**Comment by SimeonC** [comment]
I think your problem is the casing in the plugin name is wrong, from memory it's case sensitive (I could be remembering this wrong though). It should be `ga('require', 'displayfeatures');` not `ga('require', 'displayFeatures');` according to their docs [(reference)](https://developers.google.com/analytics/devguides/collection/analyticsjs/display-features)

**Comment by jehartzog** [comment]
You're correct, they use camelCase in some portions of those docs but for the `require` example it's definitely all lower case. Oops, good catch.
