### ISSUE TITLE
Doesn't work with Enzyme

### ISSUE THREAD

**Issue by MarcusSorealheis** [react-ga/react-ga#133]
This library does not work with Enzyme. 

I suspect that the library may not work with any testing framework because of syntax errors.

**Comment by SimeonC** [comment]
I'd agree with you on this one. I've found that in general GA doesn't work in testing due to the load script of `ga.js`.

I think we could do `ReactGA.initialize('UA-000000-01', { testGA: { spy functions here });` allowing to pass a test spy (like sinon spy) for each api function. Also this would prevent the ga code from being loaded which I think causes a fair few problems as it uses window and `parentNode` to traverse around nodes that are potentially undefined in testing.
An example usage `ReactGA.initialize('UA-000000-01', { testGA: { modalview: spyFunction1, set: spyFunction2 });`, then for the api calls that aren't defined in this we just use an empty function to prevent errors.

@yangshun What do you think about this? If you are OK with this approach I'll do a PR for it.

**Comment by christiankiely** [comment]
I've found that (if using Jest), including `jest.mock("react-ga")` at the top of a test file will fix errors.
