### ISSUE TITLE
Implement with React-Router: a different setup!

### ISSUE THREAD

**Issue by sjorsvanheuveln** [react-ga/react-ga#224]
I'm trying to implement the package with the use of react router. The issue #122 and the provided solution are not working for me as I have a different setup.

This is my setup:
```
const renderApp = (Component) => {
  render(
    <AppContainer>
      <Provider store={Store}>
        <div style={{ height: '100%' }}>
          <Component />
          { <DevTools /> }
        </div>
      </Provider>
    </AppContainer>,
    document.querySelector('#react-app'),
  );
};

renderApp(TemplateContainer);

```
And this is the proposed solution:
```
import withTracker from './withTracker';

ReactDOM.render(
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <Route component={withTracker(App, { /* additional attributes */ } )} />
    </ConnectedRouter>
  </Provider>,
  document.getElementById('root'),
);
```
As you can see, I'm using React Router in a different way. How do I hook it up in me setup? My router component is 2 components further down in the TemplateContainer.

**Comment by SimeonC** [comment]
It's just an example, the important part is; `<Route component={withTracker(App, { /* additional attributes */ } )} />` which can go anywhere. Basically, this is a route that is always matched so you can just replace `App` with whatever, it doesn't have to be this either you can just wrap all your top-level routes and that would work too. I'd recommend understanding what the `withTracker` HOC does in the example, then you can adapt that to whatever you want. There's no single way of doing this which is why it's not part of the library.
