### ISSUE TITLE
TypeScript type definitions do not match release documentation

### ISSUE THREAD

**Issue by dsanders1234** [react-ga/react-ga#239]
The typescript type definitions do not match the documented API

For example, in the npm 2.4.1 release, there is no TestModeAPI and ReactGA.pageview does not support a title argument as per the documentation

**Comment by rvaidya** [comment]
I also get "module has no default export" when using the recommended import statement of 
import ReactGA from 'react-ga';

since the Typescript definitions do not declare a default export.  Need to import using
import * as ReactGA from 'react-ga';

**Comment by rvaidya** [comment]
Using the master branch directly solves a lot of my issues, but I still have one more.

I am using multiple trackers and testMode is read in the initialize() function, not _initialize().  The Typescript definitions only have one argument for the multiple trackers call so testMode never gets read, since I cannot pass a second argument.

**Comment by SimeonC** [comment]
Sorry for the delay, have just pushed out a new version with the typescript definitions.

**Comment by rvaidya** [comment]
Hi @SimeonC  see my comment on testMode and using multiple trackers

Right now for simplicity I've added options to the second initialize call signature:

`export function initialize(trackers: Tracker[], options?: InitializeOptions): void;`
