### ISSUE TITLE
The tracking Id should only be of the format UA-NNNNNN-N

### ISSUE THREAD

**Issue by sm2017** [react-ga/react-ga#469]
The google analytics dashboard show my Tracking Code in `G-XXXXXXXXXX` format and the react-GA need it to be in `UA-NNNNNN-N`

Everything is works for me, google analytics can collect data now, my problem is events, when I send the following event nothing happens in dashboard

```
ReactGA.event({
  category: 'User',
  action: 'Created an Account'
});
```

Also in dashboard, when I want to Add event there is no `category` and `action` just `event name`

**Comment by romiem** [comment]
This is because you have created a Google Analytics 4 property. GA4 is not supported by react-ga as far as I know. Delete this property, and create a new one. During the creation process, there is button to see 'Advanced Options' - tick 'Universal Analytics' and this will use the older Google Analytics properties which will yield the UA-**** tracking ID.
