### ISSUE TITLE
Upgrade to Webpack, Babel, ESLint

### ISSUE THREAD

**Issue by yangshun** [react-ga/react-ga#77]
It's probably good to upgrade this project to use the common React ecosystem tools 😄

**Comment by Jac21** [comment]
Are you intending on targeting any particular versions of these tools?

**Comment by yangshun** [comment]
Yes the latest versions if possible

**Comment by blakek** [comment]
When adding eslint using the Airbnb style guide—plus other options to more closely match the current jscs config—there were several errors and warnings.  There were 175 at first, and running `eslint --fix src` brought it down to 58.  Most of these were related to using `var` instead of `let` or `const` or some other, similar ES5 vs. ES6 issue.

I guess my question is, if eslint is added, is the preference for moving to following the Airbnb ES6 style guide or is sticking with what's already there?

**Comment by yangshun** [comment]
@blakek We can use the Airbnb eslint preset (:
